### ISSUE TITLE
DistributedMesh ParmetisPartitioner interface performance is awful

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#1598]
Thanks to @bboutkov for making this easy to replicate with https://github.com/bboutkov/libmesh/commit/fb76306dc34875d45c0503c29575bd11ca53b25a

Splitting a few million elements among a few dozen processors in that uniform refinement study requires about 20 seconds spent in find_global_indices().  Splitting them among a few hundred processors requires about *2000* seconds spent in find_global_indices().

Obviously the nicest way to resolve this would be to fix find_global_indices() (and thereby speed up I/O using that method as well!) but if that's not possible we can probably avoid calling for perfectly Hilbert-sorted DofObject ids in the first place; unlike in the case of Xdr I/O we don't care about partitioning independence or N-to-M or any such thing here, we only need to meet the ParMETIS API requirements.

**Comment by roystgnr** [comment]
Parallel::sum() is a noticeable time sink in the 32 processor case, but the cost growth is O(log2(Nproc)), which may be as good as we can hope for.

Parallel::probe() calls (in the send_receive() calls in find_global_indices()) are taking a large minority of the PerfLog time at 320 processors, suggesting some load imbalance.

The majority of time spent is in the Parallel::Sort operation, and apparently *not* in communication subroutines...

**Comment by roystgnr** [comment]
Ah, never mind, it's in communication.  Sort::communicate_bins() is responsible for all the time, and makes direct MPI calls which aren't tracked by the PerfLog.

**Comment by jwpeterson** [comment]
IIRC `Parallel::Sort` is something we implemented ourselves, but it might not be the best (or even a good) algorithm for sorting in parallel? Perhaps there is a more performant "standard" implementation we could use instead?

**Comment by roystgnr** [comment]
I tried changing find_global_indices() from the naive round-robin send_receive() to sophisticated asynchronous I/O... and that actually ends up nearly doubling the amount of time I see spent in that communication!

Which is pretty dumbfounding.  Clearly my intuition here is way off.  I might still get to a faster solution along these lines by optimizing for the high N case (where most communications are empty and we can skip them) but I'm no longer optimistic.

It may be time to refactor all our instances of that sort of communication algorithm, similarly to what we already have in parallel_ghost_sync.h.  Then we can swap algorithms in and out without rewriting a hundred lines of code each time, and see what works fastest where.

**Comment by jwpeterson** [comment]
Timings for the test code from our cluster with the optimization in #1600. These are single runs, not sure how big the standard deviation in the times would be.
```
Procs, Ref1,     Ref2,     Ref3,     Ref4,    Ref5
   32, 0.074746, 0.209079, 0.791768, 3.73336, 15.6589
   64, 0.167095, 0.302664, 0.797142, 3.25649, 13.3353
  128, 0.723943, 1.170260, 1.366920, 3.15720, 12.3910
  256, 3.779990, 4.539470, 5.415170, 7.34746, 14.7930
```

**Comment by jwpeterson** [comment]
![pr_1600](https://user-images.githubusercontent.com/1775907/36810713-c64865c0-1c88-11e8-9c61-b72c8ba17abc.png)

@roystgnr Here are the results from our cluster. The optimization in #1600 looks like a win for all processor counts and all refinement levels to me, although the overall scalability of both methods obviously leaves something to be desired.

**Comment by pbauman** [comment]
Cool! I think the scalability should be fixed in #1603.

**Comment by jwpeterson** [comment]
While I have everything set up for timing, I'll also try the branch in #1603 if you think enough of the bugs have been ironed out for the performance numbers to be meaningful.

**Comment by roystgnr** [comment]
I'm not ready to merge #1603 quite yet, but I'd give better-than-50/50 odds that we'll be able to merge it as-is.  Go ahead and give it a shot.

Also: comparing your performance numbers to mine makes me much less eager to brag about how often I currently have a cluster to myself, at least not until I figure out how to tune MPI there better...

**Comment by jwpeterson** [comment]
![pr_1600_1603](https://user-images.githubusercontent.com/1775907/36814387-9242d2e0-1c94-11e8-9797-7080fae760a5.png)

New plot including the optimizations in #1603. Faster and also quite a bit better scaling out to 512 cores, looks good to me @roystgnr.

**Comment by roystgnr** [comment]
Great!

Sorry about putting you to the trouble, but it looks like I'm going to have to do the same with future parallel optimizations too.  I just found out that fixing our hand-me-down cluster's MPI performance out past 160 processors isn't going to be as simple as "compile a better-configured MPI stack", it's also going to require scrounging another infiniband switch.

So I'll still be in great shape for working on optimizing communication scalability, by being on a cluster where communication is outstandingly expensive, but we won't want to actually commit any of those proposed optimizations without testing them out on a more real-world system first.

**Comment by roystgnr** [comment]
I think #1603 counts as a fix for this.
